x-shared: &image
  image: bitnami/clickhouse:23.1.3-debian-11-r5

services:
  clickhouse01:
    <<: [*image]
    container_name: clickhouse01
    hostname: clickhouse01
    environment:
      CLICKHOUSE_SERVER_ID: 1
      ALLOW_EMPTY_PASSWORD: yes
      CLICKHOUSE_MOUNTED_DIR: /etc/clickhouse-server
    networks:
      clickhouse-network:
        ipv4_address: 172.23.23.11
    ports:
      # - "127.0.0.1:8123:8123"
      - "127.0.0.1:9032:9000"
    volumes:
      - ${PWD}/clickhouse01:/etc/clickhouse-server
  clickhouse02:
    <<: [*image]
    container_name: clickhouse02
    hostname: clickhouse02
    environment:
      CLICKHOUSE_SERVER_ID: 2
      ALLOW_EMPTY_PASSWORD: yes
      CLICKHOUSE_MOUNTED_DIR: /etc/clickhouse-server
    networks:
      clickhouse-network:
        ipv4_address: 172.23.23.12
    volumes:
      - ${PWD}/clickhouse02:/etc/clickhouse-server
  clickhouse03:
    <<: [*image]
    container_name: clickhouse03
    hostname: clickhouse03
    environment:
      CLICKHOUSE_SERVER_ID: 3
      ALLOW_EMPTY_PASSWORD: yes
      CLICKHOUSE_MOUNTED_DIR: /etc/clickhouse-server
    networks:
      clickhouse-network:
        ipv4_address: 172.23.23.13
    volumes:
      - ${PWD}/clickhouse03:/etc/clickhouse-server
  clickhouse04:
    <<: [*image]
    container_name: clickhouse04
    hostname: clickhouse04
    environment:
      CLICKHOUSE_SERVER_ID: 4
      ALLOW_EMPTY_PASSWORD: yes
      CLICKHOUSE_MOUNTED_DIR: /etc/clickhouse-server
    networks:
      clickhouse-network:
        ipv4_address: 172.23.23.14
    volumes:
      - ${PWD}/clickhouse04:/etc/clickhouse-server

networks:
  clickhouse-network:
    name: ch-network
    ipam:
      config:
        - subnet: 172.23.23.0/24
