x-shared: &image
  image: bitnami/clickhouse:24.9.1-debian-12-r2 #bitnami/clickhouse:23.1.3-debian-11-r5
  volumes:
    - ./config/config.d/:/bitnami/clickhouse/etc/conf.d/
    - ./config/users.d/:/bitnami/clickhouse/etc/users.d/

services:
  clickhouse01:
    <<: [*image]
    container_name: clickhouse01
    hostname: clickhouse01
    environment:
      CH_SHARD: 01
      ALLOW_EMPTY_PASSWORD: yes
      CLICKHOUSE_MOUNTED_DIR: /bitnami/clickhouse
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.110
  clickhouse02:
    <<: [*image]
    container_name: clickhouse02
    hostname: clickhouse02
    environment:
      CH_SHARD: 02
      ALLOW_EMPTY_PASSWORD: yes
      CLICKHOUSE_MOUNTED_DIR: /bitnami/clickhouse
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.120
  clickhouse03:
    <<: [*image]
    container_name: clickhouse03
    hostname: clickhouse03
    extra_hosts:
      - "clickhouse03:172.23.0.130"
    environment:
      CH_SHARD: 03
      ALLOW_EMPTY_PASSWORD: yes
      CLICKHOUSE_MOUNTED_DIR: /bitnami/clickhouse
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.130
  clickhouse04:
    <<: [*image]
    container_name: clickhouse04
    hostname: clickhouse04
    working_dir: /tmp
    environment:
      CH_SHARD: 04
      ALLOW_EMPTY_PASSWORD: yes
      CLICKHOUSE_MOUNTED_DIR: /bitnami/clickhouse
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.140

networks:
  clickhouse-network:
    name: ch-network
    ipam:
      config:
        - subnet: 172.23.0.0/24
