x-shared: &image
  image: bitnami/clickhouse:23.12.4-debian-11-r9 #bitnami/clickhouse:24.9.1-debian-12-r2
  environment: &env
    CLICKHOUSE_ADMIN_USER: admin
    CLICKHOUSE_ADMIN_PASSWORD: "123"
    # ALLOW_EMPTY_PASSWORD: yes
    CLICKHOUSE_MOUNTED_DIR: /bitnami/clickhouse
  volumes:
    - ./config/config.d/:/bitnami/clickhouse/etc/conf.d/
    - ./config/users.d/:/bitnami/clickhouse/etc/users.d/

services:
  clickhouse-01-01:
    <<: [*image]
    container_name: clickhouse-01-01
    hostname: clickhouse-01-01
    environment:
      <<: [*env]
      CH_SHARD: shard01
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.110
  clickhouse-01-02:
    <<: [*image]
    container_name: clickhouse-01-02
    hostname: clickhouse-01-02
    environment:
      <<: [*env]
      CH_SHARD: shard01
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.120
  clickhouse-02-01:
    <<: [*image]
    container_name: clickhouse-02-01
    hostname: clickhouse-02-01
    extra_hosts:
      - "clickhouse-02-01:172.23.0.130"
    environment:
      <<: [*env]
      CH_SHARD: shard02
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.130
  clickhouse-02-02:
    <<: [*image]
    container_name: clickhouse-02-02
    hostname: clickhouse-02-02
    environment:
      <<: [*env]
      CH_SHARD: shard02
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.140

networks:
  clickhouse-network:
    name: ch-network
    ipam:
      config:
        - subnet: 172.23.0.0/24
