x-shared: &image
  image: bitnami/clickhouse:24.9.1-debian-12-r2 #bitnami/clickhouse:23.1.3-debian-11-r5
  environment:
    # ALLOW_EMPTY_PASSWORD: yes
    HOME: /tmp
    CLICKHOUSE_MOUNTED_DIR: /bitnami/clickhouse
  command: ["--config", "/bitnami/clickhouse/etc/keeper.xml" ]
  entrypoint: ["clickhouse-keeper"]

services:
  keeper1:
    <<: [*image]
    container_name: keeper1
    hostname: keeper1
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    ports:
      - "127.0.0.1:9234:9234"
    volumes:
      - ${PWD}/volumes/keeper1:/bitnami/clickhouse/etc
  keeper2:
    <<: [*image]
    container_name: keeper2
    hostname: keeper2
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    volumes:
      - ${PWD}/volumes/keeper2:/bitnami/clickhouse/etc
  keeper3:
    <<: [*image]
    container_name: keeper3
    hostname: keeper3
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.13
    volumes:
      - ${PWD}/volumes/keeper3:/bitnami/clickhouse/etc

networks:
  clickhouse-network:
    name: ch-network
    ipam:
      config:
        - subnet: 172.23.0.0/24
