x-shared: &image
  image: bitnami/clickhouse:24.9.1-debian-12-r2 #bitnami/clickhouse:23.1.3-debian-11-r5
  volumes:
    - ./config/keeper/keeper.xml:/bitnami/clickhouse/etc/keeper.xml
  environment:
    HOME: /tmp
    CLICKHOUSE_MOUNTED_DIR: /bitnami/clickhouse
  command: ["--config", "/bitnami/clickhouse/etc/keeper.xml" ]
  entrypoint: ["clickhouse-keeper"]

services:
  keeper1:
    <<: [*image]
    container_name: keeper1
    hostname: keeper1
    environment:
      KEEPER_ID: 1
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
  keeper2:
    <<: [*image]
    container_name: keeper2
    hostname: keeper2
    environment:
      KEEPER_ID: 2
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
  keeper3:
    <<: [*image]
    container_name: keeper3
    hostname: keeper3
    environment:
      KEEPER_ID: 3
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.13

networks:
  clickhouse-network:
    name: ch-network
    ipam:
      config:
        - subnet: 172.23.0.0/24
